### ISSUE TITLE
 Reboot AX3 WS7200?

### ISSUE THREAD

**Issue by ikedinha** [vmakeev/huawei_mesh_router#11]
Would it be possible to do some control to reboot AX3 WS7200?

**Comment by vmakeev** [comment]
@ikedinha Hello! Can you try installing a component from [this branch](https://github.com/vmakeev/huawei_mesh_router/tree/feature/reboot_buttons)? I added reset buttons, but I want to make sure before release that they will work on the AX3 WS7200 too

**Comment by vmakeev** [comment]
@ikedinha did you manage to check the updated version of the component? The update is also available in the [pre-release v0.7.6-rc1](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.7.6-rc1)

**Comment by vmakeev** [comment]
@ikedinha Reboot buttons are available in the [release v0.8.0](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.8.0)

**Comment by ikedinha** [comment]
@vmakeev OK, IT'S WORKING FOR ME. THANKS
