### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by sklavosit** [vmakeev/huawei_mesh_router#21]
Please add this features : 
Sensors:
WAN IP address:
Internet connection time:
Up time:

Switches:
Internet Access switch per wireless device

**Comment by sklavosit** [comment]
Change The AX3 quad core Support to Confirmed (Yes) on Readme File

**Comment by vmakeev** [comment]
@sklavosit Thanks for the feedback!

I will add sensors in the near future, but I will have to think about internet access switches.
Creating a separate switch for each client device looks a little cumbersome (especially if there are several dozen devices on the network). I need to think about it and experiment.

**Comment by vmakeev** [comment]
@sklavosit sensors are available in [pre-release 0.8.1-rc1](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.8.1-rc1).
Could you check if the new sensors are suitable for your use cases?

p.s. switches still in progress

**Comment by sklavosit** [comment]
Thank you my 
friend !!!!

**Comment by vmakeev** [comment]
You are welcome :)
