### ISSUE TITLE
allow enable or disable guest network

### ISSUE THREAD

**Issue by weverton0800** [vmakeev/huawei_mesh_router#28]

**Comment by vmakeev** [comment]
@weverton0800 It's been a long way, and finally you can try managing the guest network (so far in the prerelease version)

https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.8.7-rc1

**Comment by vmakeev** [comment]
Update: [version 0.8.7](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.8.7) has been released
