### ISSUE TITLE
[Request]: A numeric state for how many devices are connected to guest network 

### ISSUE THREAD

**Issue by CosticaPuntaru** [vmakeev/huawei_mesh_router#3]
this can be useful for each opened network, but the guest can be nice for automations

**Comment by vmakeev** [comment]
@CosticaPuntaru , interesting suggestion, thanks.

Will sensors of the number of connected clients [in this branch](https://github.com/vmakeev/huawei_mesh_router/tree/feature/connected_devices_stats) be convenient for you?

P.S. sensors named `*interface_stats*` have additional attributes telling how many guest or hilink devices are connected to the specific interface

**Comment by CosticaPuntaru** [comment]
unfortunately, the Huawei mash network's guest mode it's completely retarded, it only turns guests on the primary router, and I can't have guests connected to it as the primary router is not in the living area, making my idea to use guests' device count unusable in my case, as I am forced to connect them to my main network,
the only thing I can do is have a list of my devices and count new connections, but this is not practical.

thx for the response and intention to help

**Comment by vmakeev** [comment]
@CosticaPuntaru 
Yes, their implementation of the guest network is terrible. I have [an idea](https://github.com/vmakeev/huawei_mesh_router/discussions/5) how to get out of the situation, maybe it will work?
