### ISSUE TITLE
unable to integrate mesh 7: Invalid handler specified

### ISSUE THREAD

**Issue by paqpaqpaq** [vmakeev/huawei_mesh_router#30]
I installed via HACS and restarted HA.
upon adding the integration, this error pops up. I cannot continue after this.

> Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

**Comment by vmakeev** [comment]
I recently came across a similar problem in Home Assistant. 

Which version of Home Assistant do you have installed? Version 2022.11.2 and below were affected by such a problem.

Try upgrading to Home Assistant 2022.12, or, if you have already updated and it didn't help, tell me the HACS version and the version of the huawei_mesh_router component that you tried to install

**Comment by paqpaqpaq** [comment]
I am on 2022.11.5
I will do an upgrade to 12.8 and let you know.

**Comment by paqpaqpaq** [comment]
yes seems to be working now!

**Comment by vmakeev** [comment]
Glad to hear it :)

Do I understand correctly that you have [Huawei Mesh 7](https://consumer.huawei.com/en/routers/wifi-mesh7/) (WS8800)? 

Can I add it to the list of supported devices, or are there any issues?

**Comment by paqpaqpaq** [comment]
Correct, WS8800.
All seems to be working as described.
