### ISSUE TITLE
2023.3

### ISSUE THREAD

**Issue by weverton0800** [vmakeev/huawei_mesh_router#36]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 09:25:04 (1 occurrences)
Last logged: 09:25:04

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for huawei_mesh_router using this method at custom_components/huawei_mesh_router/__init__.py, line 93: hass.config_entries.async_setup_platforms(config_entry, loaded_platforms)

**Comment by vmakeev** [comment]
I'll fix it in the 0.8.5, thanks
