### ISSUE TITLE
sensor failure showing router uptime

### ISSUE THREAD

**Issue by weverton0800** [vmakeev/huawei_mesh_router#41]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:503
Integration: Sensor (documentation, issues)
First occurred: 10:07:15 (4 occurrences)
Last logged: 10:07:15

Entity sensor.huawei_router_uptime_primary_router (<class 'custom_components.huawei_mesh_router.sensor.HuaweiUptimeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.huawei_router_uptime_cozinha (<class 'custom_components.huawei_mesh_router.sensor.HuaweiUptimeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.huawei_router_uptime_casa_interno (<class 'custom_components.huawei_mesh_router.sensor.HuaweiUptimeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.huawei_router_uptime_rua (<class 'custom_components.huawei_mesh_router.sensor.HuaweiUptimeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by vmakeev** [comment]
Thanks for feedback, fixed at https://github.com/vmakeev/huawei_mesh_router/pull/40
