### ISSUE TITLE
Block access to domains

### ISSUE THREAD

**Issue by mlhyyl** [vmakeev/huawei_mesh_router#46]
I have a Huawei AX 3 router and I often find myself blocking access to specific domains for specific devices or network-wide (e.g. youtube.com or bamgrid.com for Disney+ etc.) in order to control my son's TV watching. Instead of going to the **router > Security Settings > Parental Control** and manually adding/removing domains there, it would be a great feature to have it in this custom component. Adding domains to or removing them from a blacklist could be then automated easily.

**Comment by vmakeev** [comment]
Hi!
You can create the necessary filters in the router's Web UI, and turn them on or off from Home Assistant using these switches.

https://github.com/vmakeev/huawei_mesh_router/blob/master/docs/controls.md#website-filtering

Or do you fundamentally need to create/remove filters in the form of a HA service? This may not be very convenient, since it will require you to specify filter ids, since several filters can correspond to one URL

**Comment by mlhyyl** [comment]
Hi!

If I understood you correctly, you are saying if I have under Security Settings > Parental Control > Website Filtering entries defined for which device which domain is to be blocked, I can create a switch in HA, which would turn on/off the corresponding switch in the router. If that's the case, I'm struggling with creating a switch. do you have an example of how a switch template would look like e.g. for a device named XYTV and the domain example.com?

**Comment by mlhyyl** [comment]
Hi!

Sorry clicked the wrong button.

If I understood you correctly, you are saying if I have under Security Settings > Parental Control > Website Filtering entries defined for which device which domain is to be blocked, I can create a switch in HA, which would turn on/off the corresponding switch in the router. If that's the case, I'm struggling with creating a switch. do you have an example of how a switch template would look like e.g. for a device named XYTV and the domain example.com?

**Comment by vmakeev** [comment]
Just follow the documentation. You need to enable Website Filtering Switches in the [advanced settings](https://github.com/vmakeev/huawei_mesh_router#advanced-options) and the integration itself will create the necessary switches.

If something doesn't work out, let me know, we'll try to figure it out together

**Comment by mlhyyl** [comment]
Thanks, missed the advanced settings part. This is what I was looking for.
