### ISSUE TITLE
Switch between advanced configuration pages (1/2)

### ISSUE THREAD

**Issue by jotheman0303** [vmakeev/huawei_mesh_router#53]
Either I do not know how to switch between advanced configuration pages (so between 1/2 and 2/2) or it does not work anymore. How do I normally do that? I only see page 1/2 and no way to switch to 2.2... Can you help me?

**Comment by vmakeev** [comment]
Hi!
What happens if you click the "SUBMIT" button on the first settings page?

**Comment by jotheman0303** [comment]
Had to click "Submit" to get to the next advanced configuration page

**Comment by vmakeev** [comment]
I am glad that the situation was resolved successfully :)

This dialog is a part of the default Home Assistant interface. Unfortunately, this deprives me of the opportunity to make it intuitively more understandable.

Thank you for the suggestion to improve the documentation, I will definitely do it when I return from vacation =)
