### ISSUE TITLE
{"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by ITMPGIT** [vmakeev/huawei_mesh_router#58]
hi, I added the repository via hacs, but when adding the integration I get the error:
{"message":"Invalid handler specified"}

Ha version: 2023.7.3

**Comment by vmakeev** [comment]
Hello, which version of the component are you trying to install?

**Comment by ITMPGIT** [comment]
I'm using the version: v0.9.0

**Comment by vmakeev** [comment]
According to the [release notes](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.9.0), version 0.9.0 requires Home Assistant 2003.8 or higher to work.

The best option is to update Home Assistant to the latest version.

If for some reason the Home Assistant update is not included in your plans, you can install version [0.8.7.1](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.8.7.1 ), which is compatible with Home Assistant 2023.6 and higher

**Comment by ITMPGIT** [comment]
thanks for the feedback, and congrats on the integration. It worked!
