### ISSUE TITLE
Will integration work with AC2200 mesh?

### ISSUE THREAD

**Issue by Tazovsky** [vmakeev/huawei_mesh_router#67]
Will integration work with this mesh https://consumer.huawei.com/en/routers/wifi-mesh/ ? I'm asking because configuration asks for password

![image](https://github.com/vmakeev/huawei_mesh_router/assets/29068994/a7f60f16-2209-4e56-acba-828d3b1385aa)
 but when I'm login to web dashboard at 192.168.3.1 it requires password only:
 
![image](https://github.com/vmakeev/huawei_mesh_router/assets/29068994/b64d9fae-4a91-4077-8cf1-5ed450297d17)
so I have no idea what is the user

**Comment by vmakeev** [comment]
@Tazovsky do you still need help solving integration configuration issues?

**Comment by vmakeev** [comment]
A typical situation, I also don't use Huawei as my main router

Unfortunately, Huawei routers have technical restrictions on access to the administration panel. This article describes what options there are to overcome them

https://github.com/vmakeev/huawei_mesh_router/blob/master/docs/troubleshooting/wan-connection.md

**Comment by vmakeev** [comment]
@Tazovsky I'm glad to hear that!

Can you tell me if all the functions of the component are working correctly? Can I add the AC2200 to the list of supported devices?
