### ISSUE TITLE
How to Recover Router Password?

### ISSUE THREAD

**Issue by gamajunior** [vmakeev/huawei_mesh_router#68]
I've lost my password history and because of that I can't access my router's settings, so I'd like to know how I can extract the password that's stored on the HA.

**Comment by vmakeev** [comment]
Hi! 

The integration settings are stored in the file `<home_assistant_config_folder>/.storage/core.config_entries`.
This is a text file containing data in json format. 
Search for the string "huawei_mesh_router" in it, the data you need will be presented in several lines below.

**Comment by vmakeev** [comment]
@gamajunior was this information enough to solve our problem?

**Comment by gamajunior** [comment]
Yes, muito obrigado  😃
