### ISSUE TITLE
设备识别到了，但是无法开关控制

### ISSUE THREAD

**Issue by exewen** [vmakeev/huawei_mesh_router#80]
点击开关无效，一会开关状态又刷新回之前的状态
![1F8F9D9B-0B85-435F-9E73-8CD97D068DE5](https://github.com/vmakeev/huawei_mesh_router/assets/22954029/dcfa6ffc-c46b-4f2e-89a1-037ad357effa)
![5790C04A-68C1-4B6F-8141-31433B202CAE](https://github.com/vmakeev/huawei_mesh_router/assets/22954029/34431330-8284-415e-92ad-c25631182c67)

**Comment by exewen** [comment]
![54C68FB9-EC78-4AF7-B032-DC83A39E1E36](https://github.com/vmakeev/huawei_mesh_router/assets/22954029/ae5e72c8-6095-46da-ab22-230e81c9d8a8)
最新版本

**Comment by vmakeev** [comment]
Речь про переключатель доступа к Wi-Fi? Могу я попросить вас прислать логи компонента, чтобы попытаться определить причину неисправности?

**Comment by vmakeev** [comment]
Не дождался вашего ответа. Я закрою этот issue, но вы в любой момент можете создать новый, с более подробным описанием вашей проблемы, если она продолжит воспроизводиться
