### ISSUE TITLE
generate wifi access switch for wired devices

### ISSUE THREAD

**Issue by SikaiGGMU** [vmakeev/huawei_mesh_router#81]
the component generates wifi access switch for wired devices.

**Comment by vmakeev** [comment]
This is really strange behavior :)

Thanks for the hint, I will fix this in the next version of the component.

**Comment by vmakeev** [comment]
Fixed in [this pre-release version](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.9.3-rc1).
