### ISSUE TITLE
Active and Inactive Internet Access Time Limits

### ISSUE THREAD

**Issue by gneiva** [vmakeev/huawei_mesh_router#83]
I have a HUAWEI WiFi AX3 Pro, and I would like to be able to enable and disable Internet Access Time Limits through my home assistant.

I've set up a rule in my router, but I can't find it in Home Assistant.
![Access_Time_limit](https://github.com/user-attachments/assets/99d069d7-3093-41ae-b82a-c590686f28a9)

**Comment by vmakeev** [comment]
Hi!

This feature is not implemented in the component, but I will try to add this feature.

Most likely, these will be switches (like for Wi-Fi access), and perhaps a service for setting up a schedule.

Thanks for the idea!

**Comment by gneiva** [comment]
Thank you for the update. 

I successfully added the internet access time switches and tested them in the pre-release version. The functionality works well on my device and is convenient to use. 

Thanks for your work on this!
